server:
  port: 8086
spring:
  application:
    name: notify-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hm.db.host:localhost}:${hm.db.port:3306}/hmall?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${hm.db.username:root}
    password: ${hm.db.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.hmall.notify.domain.po
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug
